apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ml-model-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-ml-model
  template:
    metadata:
      labels:
        app: my-ml-model
    spec:
    containers:
    - name: my-ml-model
      image: str2
      ports:
      - containerPort: 8501